### ISSUE TITLE
ERROR: Write data failed.

### ISSUE THREAD

**Issue by Alex6242** [alex-free/cdrdao-pled#1]
Hi, first of all thank you for your great website. Thanks to you I was able to recondition my PS1 drive and it runs like a dream.

Now to my problem: So far I have burned under Windows with CDRTools\CDRecord. However, there is a problem with the CD audio tracks. 

Now I've tried it with cdrdao-pled and a USB stick with Ubuntu but here it only writes about 5 of 20 MB during the "Writing lead-in an gap" process and then stops with the error "ERROR: Write data failed. ". I tried it with different CD-Rs and the burner "PIONEER BD-RW BDR-UD04" works without any problems under Windows. Why could it be that it doesn't work with cdrdao? 

Thank you for the help
![Screenshot from 2024-09-13 13-01-15](https://github.com/user-attachments/assets/1d5db724-74bb-409f-ae8a-141c32b2b192)

**Comment by alex-free** [comment]
> Hi, first of all thank you for your great website. Thanks to you I was able to recondition my PS1 drive and it runs like a dream.
> 
> 
> 
> Now to my problem: So far I have burned under Windows with CDRTools\CDRecord. However, there is a problem with the CD audio tracks. 
> 
> 
> 
> Now I've tried it with cdrdao-pled and a USB stick with Ubuntu but here it only writes about 5 of 20 MB during the "Writing lead-in an gap" process and then stops with the error "ERROR: Write data failed. ". I tried it with different CD-Rs and the burner "PIONEER BD-RW BDR-UD04" works without any problems under Windows. Why could it be that it doesn't work with cdrdao? 
> 
> 
> 
> Thank you for the help
> 
> ![Screenshot from 2024-09-13 13-01-15](https://github.com/user-attachments/assets/1d5db724-74bb-409f-ae8a-141c32b2b192)
> 
> 
> 
> 

Glad your PSX is working better with the refurb guide!

CDRTools/cdrecord does in fact have an issue with CD audio tracks, not just on windows but every OS.

Are you using any usb hubs or extenders in your setup?

Have you tried a different USB port?

Can you pass the -v argument (for verbose output)?

Are you using sudo to execute cdrdao-pled?

**Comment by Alex6242** [comment]
Many thanks for the quick response. 
It is an external drive that is connected to the PC with an adapter from USB-C to USB-A, as my PC does not have a USB-C port. I ran cdrdao-pled with sudo and have already tried different USB ports.

That came with the -v 3 argument:

drdao2 write --speed 4 --driver generic-mmc-raw --swap -n -v 3 'TR (v1.6).cue'
Detected SG driver version: 3.5.27
Detected SG driver version: 3.5.27
/dev/sr0: PIONEER BD-RW   BDR-UD04	Rev: 1.11
Using driver: Generic SCSI-3/MMC (raw writing) - Version 2.0 (options 0x0000)

WARNING: Unit not ready, still trying...
WARNING: Unit not ready, still trying...
Starting write CD-TEXT writing is supported.
at speed 4...
Process can be aborted with QUIT signal (usually CTRL-\).
Turning BURN-Proof on
Using 16 byte P-Q sub-channel data mode.

Cue Sheet (variant 0):
CTL/  TNO  INDEX  DATA  SCMS  MIN  SEC  FRAME
ADR               FORM
41    00    00     24    00   00   00   00
41    01    00     00    00   00   00   00
41    01    01     00    00   00   02   00
01    02    00     00    00   32   28   61
01    02    01     00    00   32   30   61
01    03    00     00    00   35   45   29
01    03    01     00    00   35   47   29
01    04    00     00    00   36   49   27
01    04    01     00    00   36   51   27
01    05    00     00    00   38   52   66
01    05    01     00    00   38   54   66
01    06    00     00    00   40   53   02
01    06    01     00    00   40   55   02
01    07    00     00    00   42   10   01
01    07    01     00    00   42   12   01
01    08    00     00    00   43   05   67
01    08    01     00    00   43   07   67
01    09    00     00    00   44   14   11
01    09    01     00    00   44   16   11
01    0a    00     00    00   44   54   17
01    0a    01     00    00   44   56   17
01    0b    00     00    00   46   13   38
01    0b    01     00    00   46   15   38
01    0c    00     00    00   46   22   00
01    0c    01     00    00   46   24   00
01    0d    00     00    00   46   36   74
01    0d    01     00    00   46   38   74
01    0e    00     00    00   46   44   02
01    0e    01     00    00   46   46   02
01    0f    00     00    00   46   56   07
01    0f    01     00    00   46   58   07
01    10    00     00    00   47   07   10
01    10    01     00    00   47   09   10
01    11    00     00    00   47   45   73
01    11    01     00    00   47   47   73
01    12    00     00    00   48   28   62
01    12    01     00    00   48   30   62
01    13    00     00    00   48   54   11
01    13    01     00    00   48   56   11
01    14    00     00    00   50   22   56
01    14    01     00    00   50   24   56
01    15    00     00    00   51   16   73
01    15    01     00    00   51   18   73
01    16    00     00    00   51   58   15
01    16    01     00    00   52   00   15
01    17    00     00    00   53   01   53
01    17    01     00    00   53   03   53
01    18    00     00    00   53   59   22
01    18    01     00    00   54   01   22
01    19    00     00    00   54   14   50
01    19    01     00    00   54   16   50
01    1a    00     00    00   54   51   38
01    1a    01     00    00   54   53   38
01    1b    00     00    00   54   58   39
01    1b    01     00    00   55   00   39
01    1c    00     00    00   55   05   40
01    1c    01     00    00   55   07   40
01    1d    00     00    00   55   12   40
01    1d    01     00    00   55   14   40
01    1e    00     00    00   55   19   41
01    1e    01     00    00   55   21   41
01    1f    00     00    00   55   27   39
01    1f    01     00    00   55   29   39
01    20    00     00    00   55   34   40
01    20    01     00    00   55   36   40
01    21    00     00    00   55   44   03
01    21    01     00    00   55   46   03
01    22    00     00    00   55   53   45
01    22    01     00    00   55   55   45
01    23    00     00    00   56   01   17
01    23    01     00    00   56   03   17
01    24    00     00    00   56   08   31
01    24    01     00    00   56   10   31
01    25    00     00    00   56   25   27
01    25    01     00    00   56   27   27
01    26    00     00    00   56   32   28
01    26    01     00    00   56   34   28
01    27    00     00    00   56   39   29
01    27    01     00    00   56   41   29
01    28    00     00    00   56   55   35
01    28    01     00    00   56   57   35
01    29    00     00    00   57   06   00
01    29    01     00    00   57   08   00
01    2a    00     00    00   57   13   01
01    2a    01     00    00   57   15   01
01    2b    00     00    00   57   20   01
01    2b    01     00    00   57   22   01
01    2c    00     00    00   57   29   14
01    2c    01     00    00   57   31   14
01    2d    00     00    00   57   37   38
01    2d    01     00    00   57   39   38
01    2e    00     00    00   57   47   29
01    2e    01     00    00   57   49   29
01    2f    00     00    00   57   54   30
01    2f    01     00    00   57   56   30
01    30    00     00    00   58   01   31
01    30    01     00    00   58   03   31
01    31    00     00    00   58   08   32
01    31    01     00    00   58   10   32
01    32    00     00    00   58   24   28
01    32    01     00    00   58   26   28
01    33    00     00    00   58   31   28
01    33    01     00    00   58   33   28
01    34    00     00    00   58   38   28
01    34    01     00    00   58   40   28
01    35    00     00    00   58   45   29
01    35    01     00    00   58   47   29
01    36    00     00    00   58   54   49
01    36    01     00    00   58   56   49
01    37    00     00    00   59   01   50
01    37    01     00    00   59   03   50
01    38    00     00    00   59   11   29
01    38    01     00    00   59   13   29
01    39    00     00    00   59   18   30
01    39    01     00    00   59   20   30
01    aa    01     01    00   62   37   30
Session format: 20
Executing power calibration...
Power calibration successful.
Waiting for reader process
Buffer filled
Awaken, will start writing
Writing lead-in and gap...
ERROR: Write data failed.

**Comment by alex-free** [comment]
Are you executing cdrdao or cdrdao2 in the release? Should be cdrdao.

It is possible that this drive doesn't work with generic-mmc-raw. You could try

sudo cdrdao write --speed 4 --swap -n --eject *.cue

**Comment by Alex6242** [comment]
Great, that was the solution! 

Without "--driver generic-mmc-raw" it now worked perfectly and the sound works without any problems on the PS1. Thanks again for the help and the great website!!!

**Comment by alex-free** [comment]
> Great, that was the solution! 
> 
> 
> 
> Without "--driver generic-mmc-raw" it now worked perfectly and the sound works without any problems on the PS1. Thanks again for the help and the great website!!!

Glad we had success. I'll update the page to mention that the generic-mmc-raw driver may not work for newer drives and if so to try the generic-mmc driver.
